# --- XMeta test specific parameters ---

# determine whether meta_train or meta_test
meta_train: False
meta_test: True

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"
batch_size_run: 1

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "xtrans_learner"
double_q: True
mixer: "attn2_hx"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

agent: "sotax"

# params about observation decomposition
id_length: 4
max_agent: 15

# params about task_encoder
dynamic_encoder: "pooling"
dynamic_decoder: "mlp"
task_repre_dim: 32

state_latent_dim: 32

pretrain: True
dynamic_learning_end: 50000
save_repre: True
save_repre_interval: 1000
only_repre_learning: False

# params about xtrans mixing network
entity_embed_dim: 64
attn_embed_dim: 8

# mac
mac: "xtrans_mac"

# params related with transfer training
breakpoint_training: False
few_shot_adaptation: True
transfer_training: True

evaluate: True
checkpoint_path: ""


name: "xtrans_test"

